export const database: {[key: string]: any[]} = {
    fermentable: [
        {
            name: 'Bohemian Pilsner',
            type: 'Grain',
            yield: 81,
            color: 2.0,
        },
        {
            name: 'Brown Sugar (Light)',
            type: 'Sugar',
            yield: 100,
            color: 8.0,
        },
        {
            name: 'Cara Malt',
            type: 'Grain',
            yield: 75,
            color: 15.0,
        },
        {
            name: 'Caraamber',
            type: 'Grain',
            yield: 78,
            color: 27.0,
        },
        {
            name: 'Caraaroma',
            type: 'Grain',
            yield: 77,
            color: 130.0,
        },
        {
            name: 'Carafa I',
            type: 'Grain',
            yield: 70,
            color: 330.0,
        },
        {
            name: 'Carafa II',
            type: 'Grain',
            yield: 70,
            color: 425.0,
        },
        {
            name: 'Carafa III',
            type: 'Grain',
            yield: 70,
            color: 520.0,
        },
        {
            name: 'Carafoam',
            type: 'Grain',
            yield: 81,
            color: 2.0,
        },
        {
            name: 'Carahell',
            type: 'Grain',
            yield: 79,
            color: 10.0,
        },
        {
            name: 'Caramunich I',
            type: 'Grain',
            yield: 78,
            color: 35.0,
        },
        {
            name: 'Caramunich II',
            type: 'Grain',
            yield: 78,
            color: 45.0,
        },
        {
            name: 'Caramunich III',
            type: 'Grain',
            yield: 78,
            color: 57.0,
        },
        {
            name: 'Carared',
            type: 'Grain',
            yield: 78,
            color: 18.0,
        },
        {
            name: 'Carawheat',
            type: 'Grain',
            yield: 77,
            color: 44.0,
        },
        {
            name: 'Corn Syrup',
            type: 'Sugar',
            yield: 78,
            color: 0.0,
        },
        {
            name: 'Crystal (Extra Dark) ',
            type: 'Grain',
            yield: 71,
            color: 173.0,
        },
        {
            name: 'Crystal Malt',
            type: 'Grain',
            yield: 75,
            color: 65.0,
        },
        {
            name: 'Crystal Malt (Dark)',
            type: 'Grain',
            yield: 72,
            color: 150.0,
        },
        {
            name: 'Crystal Malt (Pale)',
            type: 'Grain',
            yield: 75,
            color: 30.0,
        },
        {
            name: 'Crystal Rye Malt',
            type: 'Grain',
            yield: 75,
            color: 75.0,
        },
        {
            name: 'Golden Promise',
            type: 'Grain',
            yield: 81,
            color: 2.0,
        },
        {
            name: 'Golden Syrup',
            type: 'Sugar',
            yield: 100,
            color: 50.0,
        },
        {
            name: 'Lager Malt',
            type: 'Grain',
            yield: 83,
            color: 2.0,
        },
        {
            name: 'Marris Otter',
            type: 'Grain',
            yield: 83,
            color: 3.0,
        },
        {
            name: 'Meladoidin Malt',
            type: 'Grain',
            yield: 81,
            color: 27.0,
        },
        {
            name: 'Munich 10L Malt',
            type: 'Grain',
            yield: 77,
            color: 10.0,
        },
        {
            name: 'Munich 20L Malt',
            type: 'Grain',
            yield: 75,
            color: 20.0,
        },
        {
            name: 'Optic',
            type: 'Grain',
            yield: 80,
            color: 3.0,
        },
        {
            name: 'Pale Ale',
            type: 'Grain',
            yield: 85,
            color: 3.0,
        },
        {
            name: 'Pale Chocolate Malt',
            type: 'Grain',
            yield: 71,
            color: 250.0,
        },
        {
            name: 'Pilsner',
            type: 'Grain',
            yield: 81,
            color: 2.0,
        },
        {
            name: 'Smoked Malt',
            type: 'Grain',
            yield: 81,
            color: 2.0,
        },
        {
            name: 'Acide (Malt)',
            type: 'Grain',
            yield: 58,
            color: 2.0,
        },
        {
            name: 'Amber (Malt)',
            type: 'Grain',
            yield: 80,
            color: 50.0,
        },
        {
            name: 'Biscuit (Malt)',
            type: 'Grain',
            yield: 79,
            color: 30.0,
        },
        {
            name: 'Black (Malt)',
            type: 'Grain',
            yield: 71,
            color: 660.0,
        },
        {
            name: 'Brown (Malt)',
            type: 'Grain',
            yield: 71,
            color: 75.0,
        },
        {
            name: 'Chocolat (Malt)',
            type: 'Grain',
            yield: 71,
            color: 500.0,
        },
        {
            name: 'Froment Chocolat',
            type: 'Grain',
            yield: 74,
            color: 375.0,
        },
        {
            name: 'Froment Blond (Malt)',
            type: 'Grain',
            yield: 80,
            color: 2.0,
        },
        {
            name: 'Tourbé (Malt)',
            type: 'Grain',
            yield: 74,
            color: 2.0,
        },
        {
            name: 'Vienna (Malt)',
            type: 'Grain',
            yield: 78,
            color: 4.0,
        },
        {
            name: 'Munich (Malt)',
            type: 'Grain',
            yield: 80,
            color: 9.0,
        },
        {
            name: 'Seigle Blond (Malt)',
            type: 'Grain',
            yield: 63,
            color: 3.0,
        },
        {
            name: 'Avoine Blond (Malt)',
            type: 'Grain',
            yield: 80,
            color: 2.0,
        },
        {
            name: 'Mild Ale (Malt)',
            type: 'Grain',
            yield: 80,
            color: 4.0,
        },
        {
            name: 'Caragold',
            type: 'Grain',
            yield: 74,
            color: 61.0,
        },
        {
            name: 'Froment, Crystal (Malt)',
            type: 'Grain',
            yield: 75,
            color: 63.0,
        },
        {
            name: 'Seigle, Crystal (Malt)',
            type: 'Grain',
            yield: 75,
            'addAferBoil': false,
            color: 75.0,
        },
        {
            name: 'Orge Grillée',
            type: 'Grain',
            yield: 69,
            color: 610.0,
        },
        {
            name: 'Seigle Grillée (Malt)',
            type: 'Grain',
            yield: 69,
            color: 250.0,
        },
        {
            name: 'Froment Grillé (Malt)',
            type: 'Grain',
            yield: 71,
            color: 500.0,
        },
        {
            name: 'Aromatique (Malt)',
            type: 'Grain',
            yield: 78,
            color: 25.0,
        },
        {
            name: 'Special B',
            type: 'Grain',
            yield: 65,
            color: 152.0,
        },
        {
            name: 'Rauch (Malt)',
            type: 'Grain',
            yield: 77,
            color: 2.0,
        },
        {
            name: 'Carapils',
            type: 'Grain',
            yield: 75,
            color: 3.0,
        },
        {
            name: 'Carabelge',
            type: 'Grain',
            yield: 74,
            color: 16.0,
        },
        {
            name: 'Cara Bohemian',
            type: 'Grain',
            yield: 73,
            color: 102.0,
        },
        {
            name: 'Carafa Special I',
            type: 'Grain',
            yield: 65,
            color: 457.0,
        },
        {
            name: 'Carafa Special II',
            type: 'Grain',
            yield: 65,
            color: 609.0,
        },
        {
            name: 'Carafa Special III',
            type: 'Grain',
            yield: 65,
            color: 711.0,
        },
        {
            name: 'Epautre (Malt)',
            type: 'Grain',
            yield: 80,
            color: 3.0,
        },
        {
            name: 'Froment Torréfié',
            type: 'Grain',
            yield: 73,
            color: 2.0,
        },
        {
            name: 'Froment, fumé au chêne (Malt)',
            type: 'Grain',
            yield: 81,
            color: 3.0,
        },
        {
            name: 'Avoine, flocons',
            type: 'Grain',
            yield: 80,
            color: 1.0,
        },
        {
            name: 'Orge, flocons',
            type: 'Grain',
            yield: 60,
            color: 2.0,
        },
        {
            name: 'Maïs, flocons',
            type: 'Grain',
            yield: 60,
            color: 2.0,
        },
        {
            name: 'Extrait en poudre Amber',
            type: 'Dry Extract',
            yield: 95,
            color: 9.0,
        },
        {
            name: 'Extrait en poudre Black',
            type: 'Dry Extract',
            yield: 95,
            color: 48.0,
        },
        {
            name: 'Extrait en poudre Blond',
            type: 'Dry Extract',
            yield: 95,
            color: 4.0,
        },
        {
            name: 'Extrait en poudre Foncé',
            type: 'Dry Extract',
            yield: 95,
            color: 29.0,
        },
        {
            name: 'Extrait en poudre Froment',
            type: 'Dry Extract',
            yield: 95,
            color: 4.0,
        },
        {
            name: 'Extrait liquide Blond',
            type: 'Extract',
            yield: 80,
            color: 5.0,
        },
        {
            name: 'Extrait liquide Foncé',
            type: 'Extract',
            yield: 80,
            color: 28.0,
        },
        {
            name: 'Extrait liquide Froment',
            type: 'Extract',
            yield: 80,
            color: 4.0,
        },
        {
            name: 'Extrait liquide Amber',
            type: 'Extract',
            yield: 80,
            color: 9.0,
        },
        {
            name: 'Malt d\'orge Fumé',
            type: 'Grain',
            yield: 81,
            color: 2.0,
        },
        {
            name: 'Corn Sugar',
            type: 'Sugar',
            yield: 100,
            color: 0.0,
        },
    ],
    hop: [
        {
            name: 'Admiral',
            alpha: 15,
            form: 'Leaf',
        },
        {
            name: 'Ahtanum',
            alpha: 6,
            form: 'Leaf',
        },
        {
            name: 'Amarillo',
            alpha: 9,
            form: 'Leaf',
        },
        {
            name: 'Aquila',
            alpha: 7,
            form: 'Leaf',
        },
        {
            name: 'Banner',
            alpha: 10,
            form: 'Leaf',
        },
        {
            name: 'Bramling Cross',
            alpha: 6,
            form: 'Leaf',
        },
        {
            name: 'Brewer\'s Gold',
            alpha: 8,
            form: 'Leaf',
        },
        {
            name: 'Bullion',
            alpha: 8,
            form: 'Leaf',
        },
        {
            name: 'Cascade',
            alpha: 6,
            form: 'Leaf',
        },
        {
            name: 'Centennial',
            alpha: 10,
            form: 'Leaf',
        },
        {
            name: 'Challenger',
            alpha: 8,
            form: 'Leaf',
        },
        {
            name: 'Chinook',
            alpha: 13,
            form: 'Leaf',
        },
        {
            name: 'Cluster',
            alpha: 7,
            form: 'Leaf',
        },
        {
            name: 'Columbia',
            alpha: 6,
            form: 'Leaf',
        },
        {
            name: 'Columbus',
            alpha: 14,
            form: 'Leaf',
        },
        {
            name: 'Comet',
            alpha: 10,
            form: 'Leaf',
        },
        {
            name: 'Copy of Warrior',
            alpha: 15,
            form: 'Leaf',
        },
        {
            name: 'Crystal',
            alpha: 4,
            form: 'Leaf',
        },
        {
            name: 'Eroica',
            alpha: 13,
            form: 'Leaf',
        },
        {
            name: 'First Gold',
            alpha: 8,
            form: 'Leaf',
        },
        {
            name: 'Galena',
            alpha: 13,
            form: 'Leaf',
        },
        {
            name: 'Glacier',
            alpha: 6,
            form: 'Leaf',
        },
        {
            name: 'Hallertauer Hersbrucker',
            alpha: 4,
            form: 'Leaf',
        },
        {
            name: 'Hallertauer Mittelfrueh',
            alpha: 4,
            form: 'Leaf',
        },
        {
            name: 'Herald',
            alpha: 12,
            form: 'Leaf',
        },
        {
            name: 'Horizon',
            alpha: 12,
            form: 'Leaf',
        },
        {
            name: 'Liberty',
            alpha: 4,
            form: 'Leaf',
        },
        {
            name: 'Lublin',
            alpha: 5,
            form: 'Leaf',
        },
        {
            name: 'Magnum',
            alpha: 14,
            form: 'Leaf',
        },
        {
            name: 'Mt. Hood',
            alpha: 6,
            form: 'Leaf',
        },
        {
            name: 'Nelson Sauvin',
            alpha: 13,
            form: 'Leaf',
        },
        {
            name: 'Northdown',
            alpha: 9,
            form: 'Leaf',
        },
        {
            name: 'Nugget',
            alpha: 13,
            form: 'Leaf',
        },
        {
            name: 'Orion',
            alpha: 7,
            form: 'Leaf',
        },
        {
            name: 'Pacific Gem',
            alpha: 15,
            form: 'Leaf',
        },
        {
            name: 'Pearle ',
            alpha: 8,
            form: 'Leaf',
        },
        {
            name: 'Pilgrim',
            alpha: 12,
            form: 'Leaf',
        },
        {
            name: 'Pioneer',
            alpha: 9,
            form: 'Leaf',
        },
        {
            name: 'Pride of Ringwood',
            alpha: 9,
            form: 'Leaf',
        },
        {
            name: 'Progress',
            alpha: 6,
            form: 'Leaf',
        },
        {
            name: 'Saaz',
            alpha: 4,
            form: 'Leaf',
        },
        {
            name: 'Santiam',
            alpha: 6,
            form: 'Leaf',
        },
        {
            name: 'Select Spalt',
            alpha: 5,
            form: 'Leaf',
        },
        {
            name: 'Simcoe',
            alpha: 13,
            form: 'Leaf',
        },
        {
            name: 'Sorachi',
            alpha: 15,
            form: 'Leaf',
        },
        {
            name: 'Southern Cross',
            alpha: 13,
            form: 'Leaf',
        },
        {
            name: 'Spalter',
            alpha: 5,
            form: 'Leaf',
        },
        {
            name: 'Sterling',
            alpha: 8,
            form: 'Leaf',
        },
        {
            name: 'Sticklebract',
            alpha: 14,
            form: 'Leaf',
        },
        {
            name: 'Strisslespalt',
            alpha: 4,
            form: 'Leaf',
        },
        {
            name: 'Styrian Goldings',
            alpha: 5,
            form: 'Leaf',
        },
        {
            name: 'Sun',
            alpha: 14,
            form: 'Leaf',
        },
        {
            name: 'Super alpha',
            alpha: 13,
            form: 'Leaf',
        },
        {
            name: 'Target',
            alpha: 11,
            form: 'Leaf',
        },
        {
            name: 'Tettnang',
            alpha: 5,
            form: 'Leaf',
        },
        {
            name: 'Tradition',
            alpha: 6,
            form: 'Leaf',
        },
        {
            name: 'Ultra',
            alpha: 3,
            form: 'Leaf',
        },
        {
            name: 'Vanguard',
            alpha: 6,
            form: 'Leaf',
        },
        {
            name: 'Warrior',
            alpha: 15,
            form: 'Leaf',
        },
        {
            name: 'Williamette',
            alpha: 6,
            form: 'Leaf',
        },
        {
            name: 'Zeus',
            alpha: 14,
            form: 'Pellet',
        },
        {
            name: 'Apollo',
            form: 'Leaf',
            alpha: 17.0,
        },
        {
            name: 'Aramis',
            form: 'Leaf',
            alpha: 8.5,
        },
        {
            name: 'Atlas',
            form: 'Leaf',
            alpha: 7.0,
        },
        {
            name: 'Aurora',
            form: 'Plug',
            alpha: 7.0,
        },
        {
            name: 'Endeavour',
            form: 'Leaf',
            alpha: 9.5,
        },
        {
            name: 'WGV',
            form: 'Leaf',
            alpha: 6.5,
        },
        {
            name: 'Beata',
            form: 'Leaf',
            alpha: 4.5,
        },
        {
            name: 'Boadicea',
            form: 'Leaf',
            alpha: 8.5,
        },
        {
            name: 'Fuggle',
            form: 'Leaf',
            alpha: 5.0,
        },
        {
            name: 'Goldings',
            form: 'Leaf',
            alpha: 7.0,
        },
        {
            name: 'Sovereign',
            form: 'Leaf',
            alpha: 5.5,
        },
        {
            name: 'Phoenix',
            form: 'Leaf',
            alpha: 10.0,
        },
        {
            name: 'Pilot',
            form: 'Leaf',
            alpha: 9.5,
        },
        {
            name: 'Motueka',
            form: 'Leaf',
            alpha: 7.0,
        },
        {
            name: 'Agnus',
            form: 'Leaf',
            alpha: 12.0,
        },
        {
            name: 'East Kent Goldings',
            form: 'Leaf',
            alpha: 5.0,
        },
        {
            name: 'Flyer',
            form: 'Leaf',
            alpha: 11.0,
        },
        {
            name: 'Sussex ',
            form: 'Leaf',
            alpha: 7.0,
        },
        {
            name: 'Belma',
            form: 'Leaf',
            alpha: 12.0,
        },
        {
            name: 'Bravo',
            form: 'Leaf',
            alpha: 17.0,
        },
        {
            name: 'Calypso',
            form: 'Leaf',
            alpha: 17.0,
        },
        {
            name: 'Citra',
            form: 'Leaf',
            alpha: 15.0,
        },
        {
            name: 'Delta',
            form: 'Leaf',
            alpha: 6.5,
        },
        {
            name: 'El Dorado',
            form: 'Leaf',
            alpha: 16.0,
        },
        {
            name: 'Multihead',
            form: 'Leaf',
            alpha: 4.0,
        },
        {
            name: 'Newport',
            form: 'Leaf',
            alpha: 13.0,
        },
        {
            name: 'Sonnet',
            form: 'Leaf',
            alpha: 4.0,
        },
        {
            name: 'Summit',
            form: 'Leaf',
            alpha: 16.0,
        },
        {
            name: 'Bobek',
            form: 'Leaf',
            alpha: 5.0,
        },
        {
            name: 'Celeia',
            form: 'Leaf',
            alpha: 5.0,
        },
        {
            name: 'Junga',
            form: 'Leaf',
            alpha: 12.0,
        },
        {
            name: 'Mandarina Baveria',
            form: 'Leaf',
            alpha: 7.5,
        },
        {
            name: 'Northern Brewer',
            form: 'Leaf',
            alpha: 8.0,
        },
        {
            name: 'Vital',
            form: 'Leaf',
            alpha: 10.0,
        },
        {
            name: 'Galaxy',
            form: 'Leaf',
            alpha: 15.0,
        },
        {
            name: 'Green Bullet',
            form: 'Leaf',
            alpha: 13.0,
        },
        {
            name: 'Motueka',
            form: 'Leaf',
            alpha: 8.0,
        },
        {
            name: 'Stella ',
            form: 'Leaf',
            alpha: 16.0,
        },
        {
            name: 'Summer',
            form: 'Leaf',
            alpha: 6.5,
        },
    ],
    aroma: [
        {
            name: 'Badiane',
            type: 'Spice',
        },
        {
            name: 'Cannelle moulue',
            type: 'Spice',
        },
        {
            name: 'Copeaux de chêne',
            type: 'Flavor',
        },
        {
            name: 'Coriandre',
            type: 'Spice',
        },
        {
            name: 'Zeste d\'orange',
            type: 'Flavor',
        },
    ],
    misc: [
        {
            name: 'Gélatine',
            type: 'Fining',
        },
        {
            name: 'Irish Moss',
            type: 'Fining',
        },
        {
            name: 'Nutriment levures',
            type: 'Other',
        },
        {
            name: 'Whirlfloc',
            type: 'Fining',
        },
        {
            name: 'Gypse',
            type: 'Water Agent',
        },
    ],
    yeast: [
        {
            name: 'American Ale',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'American Ale',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 77,
        },
        {
            name: 'American Ale II',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 74,
        },
        {
            name: 'American Lager',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'American Wheat',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 76,
        },
        {
            name: 'Antwerp Ale',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 77,
        },
        {
            name: 'Bavarian Lager',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'Bavarian Wheat',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 73,
        },
        {
            name: 'Bavarian Wheat Blend',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'Belgian Abbey',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 76,
        },
        {
            name: 'Belgian Abbey II',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'Belgian Ardennes',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 74,
        },
        {
            name: 'Belgian Golden Ale',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 76,
        },
        {
            name: 'Belgian Lager',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 75,
        },
        {
            name: 'Belgian Lambic Blend',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'Belgian Saison',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 78,
        },
        {
            name: 'Belgian Saison I',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 70,
        },
        {
            name: 'Belgian Sour Mix I',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 75,
        },
        {
            name: 'Belgian Strong Ale',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 76,
        },
        {
            name: 'Belgian Wheat',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 74,
        },
        {
            name: 'Belgian Wit Ale',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 76,
        },
        {
            name: 'Belgian Witbier',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 74,
        },
        {
            name: 'Berlinerweisse Blend',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 77,
        },
        {
            name: 'Bohemian Lager',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'Brettanomyces bruxellensis',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'Brettanomyces lambicus',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'British Ale',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 74,
        },
        {
            name: 'British Ale',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 72,
        },
        {
            name: 'British Ale II',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'Budvar Lager',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 73,
        },
        {
            name: 'Burton Ale',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 72,
        },
        {
            name: 'California Lager',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 69,
        },
        {
            name: 'Californian Ale',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 77,
        },
        {
            name: 'Californian V Ale',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 73,
        },
        {
            name: 'Czech Budejovice Lager',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 77,
        },
        {
            name: 'Czech Pils',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 72,
        },
        {
            name: 'Danish Lager',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'Denny\'s Favorite 50',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'Dry English Ale',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 75,
        },
        {
            name: 'Edinburgh Scottish Ale',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 73,
        },
        {
            name: 'English Ale',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 77,
        },
        {
            name: 'Essex Ale',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 69,
        },
        {
            name: 'European Ale',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 69,
        },
        {
            name: 'Forbidden Fruit',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 74,
        },
        {
            name: 'French Saison',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 80,
        },
        {
            name: 'German Ale',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'German Bock Lager',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 73,
        },
        {
            name: 'German Kolsch Ale',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 75,
        },
        {
            name: 'German Lager',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 77,
        },
        {
            name: 'German Wheat',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 73,
        },
        {
            name: 'Hefeweizen',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 74,
        },
        {
            name: 'Hefeweizen IV',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 77,
        },
        {
            name: 'Irish Ale',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 73,
        },
        {
            name: 'Irish Ale',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 72,
        },
        {
            name: 'Kolsch',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'Lactobacillus',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'London Ale',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'London Ale',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 71,
        },
        {
            name: 'London Ale III',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 73,
        },
        {
            name: 'London ESB Ale',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 69,
        },
        {
            name: 'Munich Lager',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 72,
        },
        {
            name: 'Northwest Ale',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 69,
        },
        {
            name: 'Octoberfest Lager Blend',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'Pediococcus',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'Pilsen Lager',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 73,
        },
        {
            name: 'Pilsner Lager',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 75,
        },
        {
            name: 'Ringwood Ale',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 70,
        },
        {
            name: 'Roeselare Ale Blend',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 80,
        },
        {
            name: 'Safale S04',
            form: 'Dry',
            laboratory: 'Fermentis',
            attenuation: 73,
        },
        {
            name: 'Safale S33',
            form: 'Dry',
            laboratory: 'Fermentis',
            attenuation: 73,
        },
        {
            name: 'Safale T58',
            form: 'Dry',
            laboratory: 'Fermentis',
            attenuation: 73,
        },
        {
            name: 'Safbrew',
            form: 'Dry',
            laboratory: 'Fermentis',
            attenuation: 73,
        },
        {
            name: 'Safbrew',
            form: 'Dry',
            laboratory: 'Fermentis',
            attenuation: 73,
        },
        {
            name: 'Safbrew',
            form: 'Dry',
            laboratory: 'Fermentis',
            attenuation: 73,
        },
        {
            name: 'Saflager',
            form: 'Dry',
            laboratory: 'Fermentis',
            attenuation: 73,
        },
        {
            name: 'Saflager',
            form: 'Dry',
            laboratory: 'Fermentis',
            attenuation: 73,
        },
        {
            name: 'Saflager',
            form: 'Dry',
            laboratory: 'Fermentis',
            attenuation: 74,
        },
        {
            name: 'Scottish Ale',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 71,
        },
        {
            name: 'Thames Valley Ale',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 77,
        },
        {
            name: 'Trappist Ale',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 77,
        },
        {
            name: 'Trappist High Gravity',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 76,
        },
        {
            name: 'Urquell Lager',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 74,
        },
        {
            name: 'Weihenstephan Weizen',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 75,
        },
        {
            name: 'Whitbread Ale',
            form: 'Liquid',
            laboratory: 'Wyeast',
            attenuation: 70,
        },
        {
            name: 'Abbey Ale',
            form: 'Liquid',
            laboratory: 'White Labs',
            attenuation: 78,
        },
    ],
    water: [
        {
            name: 'Tap water',
        },
        {
            name: 'Source water',
        },
        {
            name: 'Mineral water',
        },
    ],
};
